REPLACE  PROCEDURE PRD_EDW.SP_FULL_ITIN(IN TX_DATE VARCHAR(10)) 
BEGIN
DECLARE PNR_CRT_DT DATE;
DECLARE PNR_REF  VARCHAR(30);
DECLARE SEG_ID INTEGER;
DECLARE SEG_RLTV_POSN  INTEGER;
DECLARE DPT_AIRPT_CD  VARCHAR(10);
DECLARE ARRV_AIRPT_CD  VARCHAR(10);
DECLARE DPT_DT_LCL  DATE;
DECLARE DPT_TM_LCL  INTEGER;
DECLARE ARRV_DT_LCL  DATE;
DECLARE ARRV_TM_LCL  INTEGER;
DECLARE CARR_CD VARCHAR(10);
DECLARE FLT_NBR VARCHAR(10);
DECLARE SUB_CLS VARCHAR(10);
DECLARE AVG_AMT DECIMAL(18,2);
DECLARE AVG_OIL_AMT DECIMAL(18,2);

DECLARE P_PNR_CRT_DT DATE;
DECLARE P_PNR_REF  VARCHAR(30);
DECLARE P_SEG_ID INTEGER;
DECLARE P_SEG_RLTV_POSN INTEGER;
DECLARE P_DPT_AIRPT_CD VARCHAR(10);
DECLARE P_ARRV_AIRPT_CD VARCHAR(10);
DECLARE P_DPT_DT_LCL DATE;
DECLARE P_DPT_TM_LCL INTEGER;
DECLARE P_ARRV_DT_LCL DATE;
DECLARE P_ARRV_TM_LCL INTEGER;
DECLARE P_CARR_CD VARCHAR(10);
DECLARE P_FLT_NBR VARCHAR(10);
DECLARE P_SUB_CLS VARCHAR(10);
DECLARE P_AVG_AMT DECIMAL(18,2);
DECLARE P_AVG_OIL_AMT DECIMAL(18,2);   

DECLARE OD_DES VARCHAR(10);
DECLARE	OD_ORI VARCHAR(10);
DECLARE FULL_ITIN VARCHAR(100);
DECLARE STAY_MIN INTEGER;
DECLARE STAY_SEG INTEGER;
DECLARE T_AVG_AMT DECIMAL(18,2);
DECLARE T_AVG_OIL_AMT DECIMAL(18,2);
DECLARE FST_DPT_DT_LCL DATE;
DECLARE FST_DPT_FLIGHT VARCHAR(10);

DECLARE projcursor CURSOR FOR

SELECT T1.pnr_crt_dt,T1.pnr_ref, T1.SEG_ID, T1.SEG_RLTV_POSN, T1.Dpt_Airpt_Cd, T1.Arrv_Airpt_Cd,T1.Dpt_Dt_Lcl, T1.Dpt_Tm_Lcl, T1.Arrv_Dt_Lcl, T1.Arrv_Tm_Lcl, T1.Carr_Cd, T1.Flt_Nbr, T1.Sub_Cls_Cd, COALESCE(COALESCE(T2.Avg_Tkt_Amt,T100.Avg_Tkt_Amt),0) Avg_Tkt_Amt, COALESCE(COALESCE(T2.Avg_Oil_Amt,T100.Avg_Oil_Amt),0) Avg_Oil_Amt
FROM (SELECT
T1.pnr_crt_dt,T1.pnr_ref, SEG_ID,SEG_RLTV_POSN, Dpt_Airpt_Cd, Arrv_Airpt_Cd,Dpt_Dt_Lcl, Dpt_Tm_Lcl, Arrv_Dt_Lcl, Arrv_Tm_Lcl,Carr_Cd, Flt_Nbr,TRIM(Carr_Cd) || TRIM(Flt_Nbr)||TRIM(Dpt_Airpt_Cd)||TRIM(Arrv_Airpt_Cd) Flt_Prod_ID, Sub_Cls_Cd
 FROM PRD_EDW_RTV.VM_T14_PNR_PAX_SEGMT t1 INNER JOIN 
(SELECT PNR_Ref, PNR_Crt_Dt, Pax_Id FROM PRD_EDW_RTV.VM_T14_PNR_PAX_INFO WHERE Txn_Itm_Nbr_Cncl=0
QUALIFY ROW_NUMBER() OVER (PARTITION BY PNR_Ref, PNR_Crt_Dt ORDER BY Pax_Id ASC)=1) T2 ON T1.pnr_ref=T2.pnr_ref AND T1.pnr_crt_dt =T2.pnr_crt_dt AND T1.Pax_ID=T2.Pax_ID
 WHERE  T1.Txn_Itm_Nbr_Cncl = 0  AND T1.SEG_RLTV_POSN>0  AND T1.Opr_Stat_cd IN ('HK','KK','RR','TK','KL','DK','LK','DR','SA') 
--WHERE  SEG_RLTV_POSN>0  AND PAX_ID=1
 AND T1.dpt_dt_lcl+1 >= CAST(TX_DATE AS DATE FORMAT 'YYYYMMDD')
 )T1 INNER JOIN 
( 
	SELECT DISTINCT T100.pnr_crt_dt,T100.pnr_ref FROM 
	(SELECT T1.pnr_crt_dt,T1.pnr_ref ,COUNT(T1.pnr_crt_dt) Count_T1
 	FROM PRD_EDW_RTV.VM_T14_PNR_PAX_SEGMT t1 INNER JOIN 
	(SELECT PNR_Ref, PNR_Crt_Dt, Pax_Id FROM PRD_EDW_RTV.VM_T14_PNR_PAX_INFO WHERE Txn_Itm_Nbr_Cncl=0
	QUALIFY ROW_NUMBER() OVER (PARTITION BY PNR_Ref, PNR_Crt_Dt ORDER BY Pax_Id ASC)=1) T2 ON T1.pnr_ref=T2.pnr_ref AND T1.pnr_crt_dt =T2.pnr_crt_dt AND T1.Pax_ID=T2.Pax_ID
	WHERE  T1.Txn_Itm_Nbr_Cncl = 0  AND T1.SEG_RLTV_POSN>0  AND T1.Opr_Stat_cd IN ('HK','KK','RR','TK','KL','DK','LK','DR','SA') 
--	WHERE  SEG_RLTV_POSN>0  AND PAX_ID=1
 		AND T1.dpt_dt_lcl +1>= CAST(TX_DATE AS DATE FORMAT 'YYYYMMDD') GROUP BY T1.pnr_crt_dt,T1.pnr_ref ) T100
	INNER JOIN 
	(SELECT T1.pnr_crt_dt,T1.pnr_ref ,COUNT(T1.pnr_crt_dt) Count_T2
 	FROM PRD_EDW_RTV.VM_T14_PNR_PAX_SEGMT t1 INNER JOIN 
	(SELECT PNR_Ref, PNR_Crt_Dt, Pax_Id FROM PRD_EDW_RTV.VM_T14_PNR_PAX_INFO WHERE Txn_Itm_Nbr_Cncl=0
	QUALIFY ROW_NUMBER() OVER (PARTITION BY PNR_Ref, PNR_Crt_Dt ORDER BY Pax_Id ASC)=1) T2 ON T1.pnr_ref=T2.pnr_ref AND T1.pnr_crt_dt =T2.pnr_crt_dt AND T1.Pax_ID=T2.Pax_ID
	WHERE  T1.Txn_Itm_Nbr_Cncl = 0  AND T1.SEG_RLTV_POSN>0  AND T1.Opr_Stat_cd IN ('HK','KK','RR','TK','KL','DK','LK','DR','SA') 
--	 WHERE SEG_RLTV_POSN>0 AND PAX_ID=1
	GROUP BY T1.pnr_crt_dt,T1.pnr_ref ) T101 ON T100.pnr_crt_dt=T101.pnr_crt_dt AND T100.pnr_ref=T101.pnr_ref AND Count_T1=Count_T2
 ) T3 ON T1.pnr_crt_dt=T3.pnr_crt_dt AND T1.pnr_ref=T3.pnr_ref
     LEFT JOIN (SELECT Flt_Prod_Id,Book_Cls_Cd,Avg_Tkt_Amt,Avg_Oil_Amt FROM prd_edw.T06_SEGMT_AVG_FARE 
			QUALIFY ROW_NUMBER () OVER(PARTITION BY Flt_Prod_Id, Book_Cls_Cd ORDER BY Updt_Dt DESC)=1) T2
       ON   T1.Flt_Prod_Id = T2.Flt_Prod_Id
	  AND   T1.Sub_Cls_Cd = T2.Book_Cls_Cd
     LEFT JOIN (SELECT Flt_Prod_Id,Book_Cls_Cd,Avg_Tkt_Amt,Avg_Oil_Amt FROM prd_edw.T06_SEGMT_AVG_FARE 
			QUALIFY ROW_NUMBER () OVER(PARTITION BY Flt_Prod_Id, Book_Cls_Cd ORDER BY Updt_Dt DESC)=1)  T100
       ON   TRIM(T1.Dpt_Airpt_Cd)||TRIM(T1.Arrv_Airpt_Cd)= T100.Flt_Prod_Id
	  AND   T1.Sub_Cls_Cd = T100.Book_Cls_Cd
 ORDER BY T1.pnr_crt_dt, T1.pnr_ref,T1.SEG_RLTV_POSN;

SET P_PNR_CRT_DT= CAST('19000101' AS DATE FORMAT 'YYYYMMDD');
SET P_PNR_REF = '?';
--set P_PAX_ID = '?';
SET P_SEG_ID =0;
SET P_SEG_RLTV_POSN = 0;
SET P_DPT_AIRPT_CD = '?';
SET P_ARRV_AIRPT_CD = '?';
SET P_DPT_DT_LCL = CAST('19000101' AS DATE FORMAT 'YYYYMMDD');
SET P_DPT_TM_LCL = 0;
SET P_ARRV_DT_LCL = CAST('19000101' AS DATE FORMAT 'YYYYMMDD');
SET P_ARRV_TM_LCL = 0;
SET P_CARR_CD ='?';
SET P_FLT_NBR ='?';
SET P_SUB_CLS ='?';
SET P_AVG_AMT = 0;
SET P_AVG_OIL_AMT=0;
SET OD_DES = '?';
SET OD_ORI = '?';
SET FULL_ITIN ='?';
SET STAY_MIN =0;
SET STAY_SEG =0;
SET T_AVG_AMT =0;
SET T_AVG_OIL_AMT=0;



OPEN projcursor ;
FETCH projcursor   INTO PNR_CRT_DT,PNR_REF ,SEG_ID, SEG_RLTV_POSN ,DPT_AIRPT_CD ,ARRV_AIRPT_CD ,DPT_DT_LCL ,DPT_TM_LCL ,ARRV_DT_LCL ,ARRV_TM_LCL,CARR_CD ,FLT_NBR ,SUB_CLS, AVG_AMT, AVG_OIL_AMT;

DELETE FROM PRD_EDW.T99_PNR_FULL_ITINERARY_P ALL;
DELETE FROM PRD_EDW.T99_PNR_OD_P ALL;
DELETE FROM PRD_EDW.T99_OD ALL;

BEGIN

WHILE  (SQLCODE = 0) DO
  CASE
	WHEN (PNR_CRT_DT<> P_PNR_CRT_DT OR PNR_REF <> P_PNR_REF) THEN 
	  CASE WHEN P_PNR_REF <> '?' THEN
	
		--Insert Full Itinerary
        	  INSERT INTO PRD_EDW.T99_PNR_FULL_ITINERARY_P VALUES(:P_PNR_CRT_DT,:P_PNR_REF,:FST_DPT_FLIGHT,:FST_DPT_DT_LCL,:FULL_ITIN,:T_AVG_AMT,:T_AVG_OIL_AMT);
	
		--Insert OD, 
	--	  IF OD_ORI<>OD_DES THEN
			  SET OD_DES =P_ARRV_AIRPT_CD;
			  SET STAY_MIN=0;
			  INSERT INTO PRD_EDW.T99_OD VALUES(:P_PNR_CRT_DT , :P_PNR_REF, :P_SEG_ID, :P_SEG_RLTV_POSN , :P_DPT_AIRPT_CD, :P_ARRV_AIRPT_CD, :OD_ORI, :OD_DES ,:P_DPT_DT_LCL,:P_DPT_TM_LCL, :STAY_MIN, :STAY_SEG,:P_CARR_CD, :P_FLT_NBR,:P_SUB_CLS, :P_AVG_AMT,P_AVG_OIL_AMT, '', '', '','','',0);	 

	--	  END IF;

	  ELSE
	      SET STAY_SEG =0;			
	  END CASE;

	  SET STAY_SEG =0;
	  SET T_AVG_AMT =AVG_AMT;
	  SET T_AVG_OIL_AMT = AVG_OIL_AMT;
	  SET OD_ORI =DPT_AIRPT_CD;
                    SET FULL_ITIN = DPT_AIRPT_CD || '-' || ARRV_AIRPT_CD;
	  SET FST_DPT_DT_LCL=DPT_DT_LCL;
                    SET FST_DPT_FLIGHT=DPT_AIRPT_CD;
  ELSE
	  CASE 
		WHEN P_ARRV_AIRPT_CD = DPT_AIRPT_CD THEN
			SET FULL_ITIN = FULL_ITIN || '-' || ARRV_AIRPT_CD;
		ELSE
			SET FULL_ITIN = FULL_ITIN || '/' || DPT_AIRPT_CD || '-' || ARRV_AIRPT_CD;
	  END CASE;

	  SET STAY_MIN=CAST((DPT_DT_LCL-P_ARRV_DT_LCL) AS BIGINT) * 1440 +(DPT_TM_LCL/10000 *60 +DPT_TM_LCL MOD 10000 /100)-(P_ARRV_TM_LCL/10000 *60 +P_ARRV_TM_LCL MOD 10000 /100);
	  CASE WHEN STAY_MIN>=1440 THEN
		  SET OD_DES =P_ARRV_AIRPT_CD;
	  ELSE
		  SET OD_DES ='';
	  END CASE;	
	  INSERT INTO PRD_EDW.T99_OD VALUES(:P_PNR_CRT_DT , :P_PNR_REF ,:P_SEG_ID, :P_SEG_RLTV_POSN , :P_DPT_AIRPT_CD, :P_ARRV_AIRPT_CD, :OD_ORI, :OD_DES ,:P_DPT_DT_LCL,:P_DPT_TM_LCL, :STAY_MIN, :STAY_SEG,:P_CARR_CD, :P_FLT_NBR,:P_SUB_CLS, :P_AVG_AMT, P_AVG_OIL_AMT,:CARR_CD, :FLT_NBR, :SUB_CLS, :ARRV_AIRPT_CD,:AVG_AMT, :AVG_OIL_AMT);	 

	  CASE WHEN STAY_MIN>=1440 THEN
		  SET STAY_SEG =STAY_SEG+1;
		  SET OD_ORI =DPT_AIRPT_CD;
	  ELSE
		  SET STAY_SEG =STAY_SEG+0;
	  END CASE;

 	  SET T_AVG_AMT =T_AVG_AMT+AVG_AMT;
	  SET T_AVG_OIL_AMT = T_AVG_OIL_AMT+ AVG_OIL_AMT;
  END CASE;

          SET P_PNR_CRT_DT =PNR_CRT_DT;
          SET P_PNR_REF =PNR_REF;
	  SET P_SEG_ID =SEG_ID;
	  SET P_SEG_RLTV_POSN =SEG_RLTV_POSN;
	  SET P_DPT_AIRPT_CD =DPT_AIRPT_CD;
	  SET P_ARRV_AIRPT_CD =ARRV_AIRPT_CD;
	  SET P_DPT_DT_LCL =DPT_DT_LCL;
	  SET P_DPT_TM_LCL =DPT_TM_LCL;
	  SET P_ARRV_DT_LCL =ARRV_DT_LCL;
	  SET P_ARRV_TM_LCL =ARRV_TM_LCL;
	  SET P_CARR_CD =CARR_CD;
	  SET P_FLT_NBR =FLT_NBR;
	  SET P_SUB_CLS =SUB_CLS;
	  SET P_AVG_AMT =AVG_AMT;
	  SET P_AVG_OIL_AMT=AVG_OIL_AMT;

	FETCH projcursor   INTO PNR_CRT_DT,PNR_REF ,SEG_ID, SEG_RLTV_POSN ,DPT_AIRPT_CD ,ARRV_AIRPT_CD ,DPT_DT_LCL ,DPT_TM_LCL ,ARRV_DT_LCL ,ARRV_TM_LCL,CARR_CD ,FLT_NBR ,SUB_CLS,AVG_AMT,AVG_OIL_AMT;
END WHILE;
END;
CLOSE projcursor;

	--Insert Full Itinerary
	CASE WHEN SEG_RLTV_POSN > 0 THEN
		--Insert Full Itinerary
        	  INSERT INTO PRD_EDW.T99_PNR_FULL_ITINERARY_P VALUES(:P_PNR_CRT_DT,:P_PNR_REF,:FST_DPT_FLIGHT,:FST_DPT_DT_LCL,:FULL_ITIN,:T_AVG_AMT,:T_AVG_OIL_AMT);
	
		--Insert OD, 
	--	  IF OD_ORI<>OD_DES THEN
			  SET OD_DES =P_ARRV_AIRPT_CD;
			  SET STAY_MIN=0;
			  INSERT INTO PRD_EDW.T99_OD VALUES(:P_PNR_CRT_DT , :P_PNR_REF,:P_SEG_ID, :P_SEG_RLTV_POSN , :P_DPT_AIRPT_CD, :P_ARRV_AIRPT_CD,  :OD_ORI,  :OD_DES ,:P_DPT_DT_LCL,:P_DPT_TM_LCL, :STAY_MIN, :STAY_SEG,:P_CARR_CD, :P_FLT_NBR,:P_SUB_CLS, :P_AVG_AMT,:P_AVG_OIL_AMT,'', '', '','','',0);	 
	--	  END IF;
		  INSERT INTO PRD_EDW.T99_PNR_OD_P SELECT PNR_CRT_DT, PNR_REF, SEG_ID, SEG_RLTV_POSN, DPT_AIRPT_CD, ARRV_AIRPT_CD,MAX(ORI) OVER (PARTITION BY PNR_CRT_DT, PNR_REF,STAY_SEG ORDER BY SEG_RLTV_POSN DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) ORI,MAX(DES) OVER (PARTITION BY PNR_CRT_DT, PNR_REF,STAY_SEG ORDER BY SEG_RLTV_POSN DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) DES, DPT_DT_LCL,DPT_TM_LCL, STAY_MIN, CARR_CD, FLT_NBR, SUB_CLS, AVG_AMT, AVG_OIL_AMT, N_CARR_CD, N_FLT_NBR, N_SUB_CLS ,N_ARRV_AIRPT_CD, N_AVG_AMT, N_AVG_OIL_AMT FROM PRD_EDW.T99_OD;
	ELSE
		  SET STAY_SEG =STAY_SEG+0;		
	END CASE;
END;